# Generated by Django 5.2.17 on 2026-10-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_collections_search_text'),
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveintegration',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'live'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category'),
        ),
    ]
