# Generated by Django 5.2.17 on 2026-10-04 10:36

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=16)),
                ('template_key', models.CharField(max_length=64)),
                ('locale', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], max_length=2)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('to_address', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(condition=models.Q(('status', 'queued')), fields=['status', 'next_attempt_at'], name='notif_outbox_queued'), models.Index(fields=['user', '-created_at'], name='notif_outbox_user_created'), models.Index(fields=['-created_at'], name='notif_outbox_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='notifications_outbox_dedupe_unique')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=16)),
                ('locale', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key', 'channel', 'locale'),
                'constraints': [models.UniqueConstraint(fields=('key', 'channel', 'locale'), name='notifications_template_unique')],
            },
        ),
    ]
