# Generated by Django 5.2.17 on 2026-10-04 10:15

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_collections_search_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='engagement_favorite_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='engagement_favorite_one_title'), models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='engagement_favorite_user_movie'), models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='engagement_favorite_user_series')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.SmallIntegerField(choices=[(1, 'Thumbs up'), (-1, 'Thumbs down')])),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='engagement_rating_one_title'), models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='engagement_rating_user_movie'), models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='engagement_rating_user_series'), models.CheckConstraint(condition=models.Q(('value__in', (1, -1))), name='engagement_rating_value')],
            },
        ),
        migrations.CreateModel(
            name='SimilarTitle',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_rows', to='catalog.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_rows', to='catalog.series')),
                ('similar_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.movie')),
                ('similar_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.series')),
            ],
            options={
                'ordering': ('-score',),
                'indexes': [models.Index(fields=['movie', '-score'], name='engagement_similar_movie'), models.Index(fields=['series', '-score'], name='engagement_similar_series')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True), ('similar_movie__isnull', False), ('similar_series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False), ('similar_movie__isnull', True), ('similar_series__isnull', False)), _connector='OR'), name='engagement_similar_same_kind')],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_ms', models.BigIntegerField(default=0)),
                ('duration_ms', models.BigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_session_id', models.UUIDField(blank=True, null=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', '-updated_at'], name='engagement_progress_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('movie__isnull', False)), models.Q(('episode__isnull', False), ('movie__isnull', True)), _connector='OR'), name='engagement_progress_one_title'), models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='engagement_progress_user_movie'), models.UniqueConstraint(condition=models.Q(('episode__isnull', False)), fields=('user', 'episode'), name='engagement_progress_user_episode')],
            },
        ),
    ]
