# Generated by Django 5.2.17 on 2026-10-04 10:31

import apps.billing.models
import apps.core.ids
import django.contrib.postgres.constraints
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        # btree_gist, for the exclusion constraint on subscriptions.
        ('core', '0001_postgres_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('duration_months', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)])),
                ('duration_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3660)])),
                ('price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='SAR', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter an ISO 4217 currency code, e.g. SAR.')])),
                ('max_streams', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_devices', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_quality', models.PositiveSmallIntegerField(choices=[(480, '480p'), (720, '720p'), (1080, '1080p'), (2160, '2160p')], default=1080)),
                ('allow_movies', models.BooleanField(default=True)),
                ('allow_series', models.BooleanField(default=True)),
                ('allow_live', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('bandwidth_cap_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('concurrency_policy', models.CharField(choices=[('reject', 'Reject new streams'), ('kick_oldest', 'Stop the oldest stream')], default='reject', max_length=16)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_limit_per_phone', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('sort', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('categories', models.ManyToManyField(blank=True, db_table='billing_plan_category', related_name='plans', to='catalog.category')),
            ],
            options={
                'ordering': ('sort', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('void', 'Void'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('locale', models.CharField(default='ar', max_length=2)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter an ISO 4217 currency code, e.g. SAR.')])),
                ('lines', models.JSONField(default=list)),
                ('subtotal', models.PositiveIntegerField()),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('vat_amount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('prices_include_vat', models.BooleanField(default=True)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('bill_to', models.JSONField(default=dict)),
                ('seller', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.plan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('grace', 'Grace'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual (admin)'), ('payment', 'Payment'), ('trial', 'Trial'), ('import', 'Import')], max_length=16)),
                ('auto_renew', models.BooleanField(default=False)),
                ('trial_identity', models.CharField(blank=True, max_length=254)),
                ('reminded_7d_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_1d_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('rejected', 'Trial request rejected'), ('merged', 'Merged into the current subscription')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('manual', 'Manual (bank transfer or cash)'), ('stripe', 'Stripe'), ('moyasar', 'Moyasar')], max_length=16)),
                ('checkout_ref', models.CharField(blank=True, max_length=255)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('mada', 'mada'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay'), ('other', 'Other')], default='other', max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter an ISO 4217 currency code, e.g. SAR.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('manual', 'Manual (bank transfer or cash)'), ('stripe', 'Stripe'), ('moyasar', 'Moyasar')], max_length=16)),
                ('event_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.payment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_months__gt', 0), ('duration_days__gt', 0), _connector='OR'), name='billing_plan_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('max_streams__gte', 1), ('max_streams__lte', 50)), name='billing_plan_max_streams_range'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('max_devices__gte', 1), ('max_devices__lte', 50)), name='billing_plan_max_devices_range'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('max_quality__in', [480, 720, 1080, 2160])), name='billing_plan_max_quality_valid'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('status__in', ('active', 'grace'))), fields=['status'], name='billing_sub_current_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-ends_at'], name='billing_sub_user_ends'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'ends_at'], name='billing_sub_status_ends'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trial_identity'], name='billing_sub_trial_identity'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('active', 'grace', 'suspended'))), expressions=[(apps.billing.models.TsTzRange('starts_at', 'ends_at'), '&&'), ('user', '=')], name='billing_subscription_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='billing_subscription_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='billing_payment_user_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-paid_at'], name='billing_payment_status_paid'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'checkout_ref'], name='billing_payment_checkout'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='billing_payment_provider_ref_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='billing_payment_refund_within_amount'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='billing_invoice_user_created'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-created_at'], name='billing_invoice_status_created'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False)), fields=('year', 'sequence'), name='billing_invoice_year_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('vat_amount')))), name='billing_invoice_totals_add_up'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('total'))), name='billing_invoice_refund_within_total'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issued_at__isnull', False), ('number__isnull', False), ('status__in', ('paid', 'refunded'))), models.Q(models.Q(('status__in', ('paid', 'refunded')), _negated=True), ('number__isnull', True)), _connector='OR'), name='billing_invoice_numbered_when_issued'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_webhook_provider_event_unique'),
        ),
    ]
