# Generated by Django 5.2.17 on 2026-10-03 18:23

import apps.core.db
import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Integer ids for Xtream clients (category_id) come from this sequence.
        migrations.RunSQL(
            sql="CREATE SEQUENCE catalog_category_xc_id_seq",
            reverse_sql="DROP SEQUENCE IF EXISTS catalog_category_xc_id_seq",
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xc_id', models.BigIntegerField(db_default=apps.core.db.NextVal('catalog_category_xc_id_seq'), unique=True)),
                ('kind', models.CharField(choices=[('vod', 'Movies'), ('series', 'Series'), ('live', 'Live TV')], max_length=8)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('is_adult', models.BooleanField(default=False)),
                ('visible_in_xtream', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('kind', 'sort', 'name_en'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='catalog_category_kind_slug')],
            },
        ),
        # Dropping the table (or the column) drops the sequence with it.
        migrations.RunSQL(
            sql="ALTER SEQUENCE catalog_category_xc_id_seq OWNED BY catalog_category.xc_id",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
