# Generated by Django 5.2.17 on 2026-10-03 21:24

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_titles_files_reviews'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='library.library'),
        ),
        migrations.AddField(
            model_name='matchreview',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.mediafile'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.episode'),
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='credit',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season'),
        ),
        migrations.AddField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='series', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.series'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.series'),
        ),
        migrations.AddField(
            model_name='credit',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.series'),
        ),
        migrations.AddIndex(
            model_name='matchreview',
            index=models.Index(fields=['status', 'created_at'], name='catalog_review_status'),
        ),
        migrations.AddConstraint(
            model_name='matchreview',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('media_file',), name='catalog_matchreview_one_open'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', '-created_at'], name='catalog_movie_status_created'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='catalog_movie_title_trgm'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title_ar'), name='gin_trgm_ops'), name='catalog_movie_title_ar_trgm'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['xxhash64'], name='catalog_mediafile_hash'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['library', 'removed_at'], name='catalog_mediafile_active'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['state'], name='catalog_mediafile_state'),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.UniqueConstraint(fields=('library', 'storage_key'), name='catalog_mediafile_library_key'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='catalog_episode_number'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['status', '-created_at'], name='catalog_series_status_created'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='catalog_series_title_trgm'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title_ar'), name='gin_trgm_ops'), name='catalog_series_title_ar_trgm'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='catalog_season_number'),
        ),
        migrations.AddConstraint(
            model_name='mediaimage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('movie__isnull', False), ('person__isnull', True), ('season__isnull', True), ('series__isnull', True)), models.Q(('episode__isnull', True), ('movie__isnull', True), ('person__isnull', True), ('season__isnull', True), ('series__isnull', False)), models.Q(('episode__isnull', True), ('movie__isnull', True), ('person__isnull', True), ('season__isnull', False), ('series__isnull', True)), models.Q(('episode__isnull', False), ('movie__isnull', True), ('person__isnull', True), ('season__isnull', True), ('series__isnull', True)), models.Q(('episode__isnull', True), ('movie__isnull', True), ('person__isnull', False), ('season__isnull', True), ('series__isnull', True)), _connector='OR'), name='catalog_mediaimage_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='catalog_credit_one_title'),
        ),
    ]
