# Generated by Django 5.2.17 on 2026-10-04 10:14

import apps.core.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


def fill_search_text(apps, schema_editor):
    """Normalise the titles of existing movies and series (Title.compute_search_text)."""
    from apps.search.normalize import normalize

    for name in ("Movie", "Series"):
        model = apps.get_model("catalog", name)
        rows = []
        for row in model.objects.only("id", "title", "title_ar", "original_title", "alt_titles"):
            seen = {}
            for value in [row.title, row.title_ar, row.original_title, *(row.alt_titles or [])]:
                folded = normalize(value or "")
                if folded:
                    seen.setdefault(folded, None)
            row.search_text = " | ".join(seen)
            rows.append(row)
        model.objects.bulk_update(rows, ["search_text"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mediafile_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('collection', 'sort', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='series',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('search_text', name='gin_trgm_ops'), name='catalog_movie_search_trgm'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('search_text', name='gin_trgm_ops'), name='catalog_series_search_trgm'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.series'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='catalog_collectionitem_one_title'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('collection', 'movie'), name='catalog_collectionitem_movie_once'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('collection', 'series'), name='catalog_collectionitem_series_once'),
        ),
        migrations.RunPython(fill_search_text, migrations.RunPython.noop),
    ]
