# Generated by Django 5.2.17 on 2026-10-03 18:23

import apps.accounts.validators
import apps.core.ids
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='XtreamCredential',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[apps.accounts.validators.validate_e164_phone]),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Riyadh', max_length=64, validators=[apps.accounts.validators.validate_timezone]),
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ip_allow', 'Allow IP address'), ('ip_deny', 'Deny IP address'), ('cidr_deny', 'Deny network (CIDR)'), ('country_allow', 'Allow country'), ('country_deny', 'Deny country')], max_length=16)),
                ('value', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAccess',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_streams', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_devices', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_quality', models.PositiveSmallIntegerField(choices=[(480, '480p'), (720, '720p'), (1080, '1080p'), (2160, '2160p')], default=1080)),
                ('concurrency_policy', models.CharField(choices=[('reject', 'Reject new streams'), ('kick_oldest', 'Stop the oldest stream')], default='reject', max_length=16)),
                ('allow_movies', models.BooleanField(default=True)),
                ('allow_series', models.BooleanField(default=True)),
                ('allow_live', models.BooleanField(default=True)),
                ('expiry_processed_for', models.DateTimeField(blank=True, editable=False, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='+', to='catalog.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'customer access profiles',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('xtream', 'IPTV app (Xtream)'), ('web', 'Web player'), ('app', 'Mobile app')], default='xtream', max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('app_hint', models.CharField(choices=[('smarters', 'IPTV Smarters'), ('tivimate', 'TiviMate'), ('ibo', 'IBO Player'), ('xciptv', 'XCIPTV'), ('ott_navigator', 'OTT Navigator'), ('smartone', 'SmartOne'), ('iptvnator', 'IPTVnator'), ('uhf', 'UHF'), ('other', 'Other')], default='other', max_length=16)),
                ('fingerprint', models.CharField(blank=True, max_length=128)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_country', models.CharField(blank=True, max_length=2)),
                ('approved', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MfaTotp',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_encrypted', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', '-created_at'], name='accounts_user_staff_created'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_user_phone'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='xtreamcredential',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='accounts.device'),
        ),
        migrations.AddIndex(
            model_name='accessrule',
            index=models.Index(fields=['user', 'type'], name='accounts_rule_user_type'),
        ),
        migrations.AddIndex(
            model_name='customeraccess',
            index=models.Index(fields=['expires_at'], name='accounts_access_expires'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.CheckConstraint(condition=models.Q(('max_streams__gte', 1), ('max_streams__lte', 50)), name='accounts_access_max_streams_range'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.CheckConstraint(condition=models.Q(('max_devices__gte', 1), ('max_devices__lte', 50)), name='accounts_access_max_devices_range'),
        ),
        migrations.AddConstraint(
            model_name='customeraccess',
            constraint=models.CheckConstraint(condition=models.Q(('max_quality__in', [480, 720, 1080, 2160])), name='accounts_access_max_quality_valid'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'revoked_at'], name='accounts_device_user_live'),
        ),
    ]
