# Generated by Django 5.2.17 on 2026-10-03 22:30

import apps.core.ids
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_mediafile_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('compat_mp4', 'Compat MP4'), ('source', 'Source (direct play)'), ('hls_variant', 'HLS variant'), ('hls_master', 'HLS master'), ('uhd', 'UHD')], max_length=16)),
                ('storage_key', models.CharField(max_length=64)),
                ('container', models.CharField(default='mp4', max_length=8)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate', models.BigIntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=32)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('encoder_used', models.CharField(blank=True, max_length=32)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, max_length=16)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='catalog.mediafile')),
            ],
            options={
                'ordering': ('media_file', 'kind', '-height'),
            },
        ),
        migrations.CreateModel(
            name='TranscodeJob',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.CharField(choices=[('compat_mp4', 'Compat MP4')], default='compat_mp4', max_length=16)),
                ('remux', models.BooleanField(default=False)),
                ('backend', models.CharField(choices=[('cpu', 'CPU (libx264)'), ('qsv', 'Intel QSV'), ('vaapi', 'VA-API'), ('nvenc', 'NVIDIA NVENC')], default='cpu', max_length=8)),
                ('encoder', models.CharField(blank=True, max_length=32)),
                ('priority', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('progress', models.FloatField(default=0.0)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('eta_s', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_host', models.CharField(blank=True, max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('error_tail', models.TextField(blank=True)),
                ('dispatches', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcode_jobs', to='catalog.mediafile')),
                ('rendition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='media.rendition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='rendition',
            index=models.Index(fields=['status', 'kind'], name='media_rendition_status'),
        ),
        migrations.AddConstraint(
            model_name='rendition',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'hls_variant'), _negated=True), fields=('media_file', 'kind'), name='media_rendition_file_kind'),
        ),
        migrations.AddIndex(
            model_name='transcodejob',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='media_job_queue'),
        ),
        migrations.AddIndex(
            model_name='transcodejob',
            index=models.Index(fields=['-created_at'], name='media_job_recent'),
        ),
        migrations.AddConstraint(
            model_name='transcodejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('media_file', 'profile'), name='media_job_one_active'),
        ),
    ]
