# Generated by Django 5.2.17 on 2026-10-04 10:28

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models

#: Names of the progressive renditions made before names existed (ADR-0014).
_NAMES = {"compat_mp4": "compat", "source": "source", "uhd": "uhd"}


def name_existing(apps, schema_editor):
    Rendition = apps.get_model("media", "Rendition")
    for kind, name in _NAMES.items():
        Rendition.objects.filter(kind=kind, name="").update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mediafile_library'),
        ('media', '0001_renditions_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_index', models.PositiveIntegerField()),
                ('language', models.CharField(default='und', max_length=8)),
                ('codec', models.CharField(max_length=32)),
                ('channels', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('forced', models.BooleanField(default=False)),
                ('commentary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('media_file', 'stream_index'),
            },
        ),
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_index', models.PositiveIntegerField(blank=True, null=True)),
                ('external', models.BooleanField(default=False)),
                ('sidecar_path', models.CharField(blank=True, max_length=1024)),
                ('upload', models.BinaryField(blank=True, null=True)),
                ('upload_name', models.CharField(blank=True, max_length=255)),
                ('codec', models.CharField(blank=True, max_length=32)),
                ('format', models.CharField(choices=[('srt', 'SubRip'), ('vtt', 'WebVTT'), ('ass', 'ASS/SSA'), ('pgs', 'PGS (image)'), ('vobsub', 'VobSub (image)'), ('other', 'Other')], max_length=8)),
                ('language', models.CharField(default='und', max_length=8)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('forced', models.BooleanField(default=False)),
                ('hearing_impaired', models.BooleanField(default=False)),
                ('encoding', models.CharField(blank=True, max_length=32)),
                ('source_hash', models.CharField(blank=True, max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('unsupported', 'Image (burn-in only)')], default='pending', max_length=12)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('cues', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('media_file', 'external', 'stream_index', 'created_at'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='rendition',
            name='media_rendition_file_kind',
        ),
        migrations.AddField(
            model_name='rendition',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rendition',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='rendition',
            name='kind',
            field=models.CharField(choices=[('compat_mp4', 'Compat MP4'), ('source', 'Source (direct play)'), ('hls_variant', 'HLS variant'), ('hls_master', 'HLS master'), ('uhd', 'UHD'), ('thumbnails', 'Thumbnails')], max_length=16),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='profile',
            field=models.CharField(choices=[('compat_mp4', 'Compat MP4'), ('hls', 'HLS ladder'), ('uhd', 'UHD version'), ('thumbnails', 'Thumbnails'), ('subtitles', 'Subtitles')], default='compat_mp4', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='rendition',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('hls_variant', 'hls_master')), _negated=True), fields=('media_file', 'kind'), name='media_rendition_file_kind'),
        ),
        migrations.AddConstraint(
            model_name='rendition',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('hls_variant', 'hls_master'))), fields=('media_file', 'kind', 'name'), name='media_rendition_file_kind_name'),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='catalog.mediafile'),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_tracks', to='catalog.mediafile'),
        ),
        migrations.AddConstraint(
            model_name='audiotrack',
            constraint=models.UniqueConstraint(fields=('media_file', 'stream_index'), name='media_audio_file_stream'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(condition=models.Q(('stream_index__isnull', False)), fields=('media_file', 'stream_index'), name='media_subtitle_file_stream'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(condition=models.Q(('sidecar_path', ''), _negated=True), fields=('media_file', 'sidecar_path'), name='media_subtitle_file_sidecar'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(condition=models.Q(('storage_key', ''), _negated=True), fields=('media_file', 'storage_key'), name='media_subtitle_file_key'),
        ),
        migrations.RunPython(name_existing, migrations.RunPython.noop),
    ]
