# Generated by Django 5.2.17 on 2026-10-03 21:31

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=32)),
                ('title_kind', models.CharField(choices=[('movie', 'Movie'), ('episode', 'Episode')], max_length=8)),
                ('title_id', models.UUIDField()),
                ('title_name', models.CharField(blank=True, max_length=255)),
                ('rendition', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('asn', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('player', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('end_reason', models.CharField(blank=True, choices=[('stopped', 'Stopped'), ('kicked', 'Kicked'), ('expired', 'Access expired'), ('limit', 'Stream limit'), ('idle', 'Idle'), ('error', 'Error')], max_length=8)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='accounts.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['user', '-started_at'], name='playback_session_user'), models.Index(fields=['-started_at'], name='playback_session_started'), models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['last_heartbeat_at'], name='playback_session_open')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session_key',), name='playback_session_one_open_per_key'), models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('ended_at__isnull', True)), models.Q(('ended_at__isnull', False), models.Q(('end_reason', ''), _negated=True)), _connector='OR'), name='playback_session_end_reason_iff_ended')],
            },
        ),
    ]
