# Generated by Django 5.2.17 on 2026-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbacksession',
            name='title_kind',
            field=models.CharField(choices=[('movie', 'Movie'), ('episode', 'Episode'), ('live', 'Live channel'), ('catchup', 'Catch-up')], max_length=8),
        ),
    ]
