import { zodResolver } from "@hookform/resolvers/zod";
import {
  getMeDevicesListQueryKey,
  isApiError,
  useMeDevicesCreate,
  useMeDevicesXtreamCredentials,
  type MyDevice,
  type MyIssuedCredential,
} from "@smart-iptv/api-portal";
import {
  Alert,
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  Input,
  PasswordInput,
  RadioGroup,
  RadioGroupItem,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@smart-iptv/ui";
import { useQueryClient } from "@tanstack/react-query";
import { Dices } from "lucide-react";
import { useState } from "react";
import {
  useForm,
  useWatch,
  type FieldValues,
  type Path,
  type UseFormSetError,
} from "react-hook-form";
import { useTranslation } from "react-i18next";
import { z } from "zod";

import {
  APP_HINTS,
  generatePassword,
  MAC_ACTIVATED,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_PATTERN,
  USERNAME_PATTERN,
  type AppHintValue,
} from "./credentials";
import { IssuedCredentialPanel } from "./issued-credential";
import { SetupGuide } from "./setup-guide";

/** Chosen credentials are optional: empty fields are generated by the API. */
const credentialShape = {
  mode: z.enum(["generate", "choose"]),
  username: z.string().trim(),
  password: z.string(),
};

function checkChosen(
  values: { mode: "generate" | "choose"; username: string; password: string },
  context: z.RefinementCtx,
): void {
  if (values.mode !== "choose") return;
  if (!USERNAME_PATTERN.test(values.username)) {
    context.addIssue({
      code: "custom",
      path: ["username"],
      message: "devices.validation.username",
    });
  }
  if (
    values.password.length < PASSWORD_MIN_LENGTH ||
    values.password.length > PASSWORD_MAX_LENGTH
  ) {
    context.addIssue({
      code: "custom",
      path: ["password"],
      message: "devices.validation.passwordLength",
    });
  } else if (!PASSWORD_PATTERN.test(values.password)) {
    context.addIssue({
      code: "custom",
      path: ["password"],
      message: "devices.validation.passwordCharacters",
    });
  }
}

const addSchema = z
  .object({
    name: z.string().trim().max(100, "auth.validation.tooLong"),
    app_hint: z.enum(APP_HINTS),
    ...credentialShape,
  })
  .superRefine(checkChosen);
type AddValues = z.output<typeof addSchema>;

const resetSchema = z.object(credentialShape).superRefine(checkChosen);
type ResetValues = z.output<typeof resetSchema>;

/** API field error codes the form explains in the customer's language. */
const FIELD_CODES = new Set([
  "username_taken",
  "username_rule",
  "password_length",
  "password_characters",
  "password_equals_username",
]);

/** Put the API's per-field refusals on the form; true when it found any. */
function applyApiErrors<T extends FieldValues>(
  error: unknown,
  setError: UseFormSetError<T>,
): boolean {
  if (!isApiError(error) || error.code !== "VALIDATION_ERROR") return false;
  let applied = false;
  for (const field of ["username", "password", "name"] as const) {
    const code = error.fieldErrorCodes[field]?.[0];
    const message = error.fieldErrors[field]?.[0];
    if (code === undefined && message === undefined) continue;
    setError(
      field as Path<T>,
      code !== undefined && FIELD_CODES.has(code)
        ? { type: "validate", message: `devices.fieldErrors.${code}` }
        : { type: "server", message: message ?? "" },
      { shouldFocus: !applied },
    );
    applied = true;
  }
  return applied;
}

function failureKey(error: unknown): string {
  if (isApiError(error) && error.code === "DEVICE_LIMIT") return "devices.errors.DEVICE_LIMIT";
  if (isApiError(error) && error.code === "RATE_LIMITED") return "devices.errors.RATE_LIMITED";
  return "devices.errors.UNEXPECTED";
}

function CredentialFields({
  form,
  mode,
}: {
  form: ReturnType<typeof useForm<ResetValues>> | ReturnType<typeof useForm<AddValues>>;
  mode: "generate" | "choose";
}) {
  const { t } = useTranslation();
  // Both forms share these three fields; react-hook-form's types can't express that union.
  const control = form.control as unknown as ReturnType<typeof useForm<ResetValues>>["control"];
  const setValue = form.setValue as unknown as ReturnType<typeof useForm<ResetValues>>["setValue"];
  return (
    <>
      <FormField
        control={control}
        name="mode"
        render={({ field }) => (
          <FormItem>
            <FormLabel>{t("devices.add.credentials")}</FormLabel>
            <FormControl>
              <RadioGroup
                value={field.value}
                onValueChange={field.onChange}
                aria-label={t("devices.add.credentials")}
                className="grid gap-2"
              >
                <label className="flex items-start gap-3 rounded-input border border-border p-3 has-[[data-state=checked]]:border-primary">
                  <RadioGroupItem value="generate" className="mt-0.5" />
                  <span className="grid gap-0.5">
                    <span className="text-sm font-medium">{t("devices.add.generate")}</span>
                    <span className="text-xs text-muted-foreground">
                      {t("devices.add.generateHint")}
                    </span>
                  </span>
                </label>
                <label className="flex items-start gap-3 rounded-input border border-border p-3 has-[[data-state=checked]]:border-primary">
                  <RadioGroupItem value="choose" className="mt-0.5" />
                  <span className="grid gap-0.5">
                    <span className="text-sm font-medium">{t("devices.add.choose")}</span>
                    <span className="text-xs text-muted-foreground">
                      {t("devices.add.chooseHint")}
                    </span>
                  </span>
                </label>
              </RadioGroup>
            </FormControl>
          </FormItem>
        )}
      />
      {mode === "choose" ? (
        <div className="grid gap-4 sm:grid-cols-2">
          <FormField
            control={control}
            name="username"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("credential.username")}</FormLabel>
                <FormControl>
                  <Input
                    dir="ltr"
                    autoComplete="off"
                    autoCapitalize="off"
                    spellCheck={false}
                    {...field}
                  />
                </FormControl>
                <FormDescription>{t("devices.add.usernameHint")}</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <div className="flex items-center justify-between gap-2">
                  <FormLabel>{t("credential.password")}</FormLabel>
                  <Button
                    type="button"
                    variant="link"
                    size="xs"
                    onClick={() => {
                      setValue("password", generatePassword(), {
                        shouldDirty: true,
                        shouldValidate: true,
                      });
                    }}
                  >
                    <Dices aria-hidden="true" />
                    {t("devices.add.suggest")}
                  </Button>
                </div>
                <FormControl>
                  <PasswordInput dir="ltr" autoComplete="new-password" {...field} />
                </FormControl>
                <FormDescription>
                  {t("devices.add.passwordHint", { min: PASSWORD_MIN_LENGTH })}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>
      ) : null}
    </>
  );
}

/** "Add TV app": a named device with Xtream credentials, then the login once, a QR code and the app's guide. */
export function AddTvAppDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const create = useMeDevicesCreate();
  const [issued, setIssued] = useState<MyIssuedCredential | null>(null);
  const [failure, setFailure] = useState<string | null>(null);
  const form = useForm<AddValues>({
    resolver: zodResolver(addSchema),
    defaultValues: { name: "", app_hint: "smarters", mode: "generate", username: "", password: "" },
  });
  const mode = useWatch({ control: form.control, name: "mode" });
  const app = useWatch({ control: form.control, name: "app_hint" });

  function close(next: boolean): void {
    onOpenChange(next);
    if (!next) {
      // The password must not outlive the dialog.
      setIssued(null);
      setFailure(null);
      form.reset();
    }
  }

  async function onSubmit(values: AddValues): Promise<void> {
    setFailure(null);
    try {
      const credential = await create.mutateAsync({
        data: {
          ...(values.name ? { name: values.name } : {}),
          app_hint: values.app_hint,
          ...(values.mode === "choose"
            ? { username: values.username, password: values.password }
            : {}),
        },
      });
      setIssued(credential);
      void queryClient.invalidateQueries({ queryKey: getMeDevicesListQueryKey() });
    } catch (error) {
      if (!applyApiErrors(error, form.setError)) setFailure(failureKey(error));
    }
  }

  return (
    <Dialog open={open} onOpenChange={close}>
      <DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>{issued ? t("devices.add.doneTitle") : t("devices.add.title")}</DialogTitle>
          <DialogDescription>
            {issued ? t("devices.add.doneDescription") : t("devices.add.description")}
          </DialogDescription>
        </DialogHeader>
        {issued ? (
          <div className="grid gap-5">
            <IssuedCredentialPanel credential={issued} />
            <SetupGuide app={issued.device.app_hint} />
            <DialogFooter>
              <Button
                onClick={() => {
                  close(false);
                }}
              >
                {t("devices.add.finish")}
              </Button>
            </DialogFooter>
          </div>
        ) : (
          <Form {...form}>
            <form
              noValidate
              className="grid gap-4"
              onSubmit={(event) => void form.handleSubmit(onSubmit)(event)}
            >
              {failure ? <Alert tone="danger">{t(failure)}</Alert> : null}
              <div className="grid gap-4 sm:grid-cols-2">
                <FormField
                  control={form.control}
                  name="app_hint"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t("devices.add.app")}</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {APP_HINTS.map((hint: AppHintValue) => (
                            <SelectItem key={hint} value={hint}>
                              {t(`devices.apps.${hint}`)}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t("devices.add.name")}</FormLabel>
                      <FormControl>
                        <Input placeholder={t("devices.add.namePlaceholder")} {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              {MAC_ACTIVATED.has(app) ? (
                <Alert tone="warning">{t("devices.macWarning")}</Alert>
              ) : null}
              <CredentialFields form={form} mode={mode} />
              <DialogFooter>
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => {
                    close(false);
                  }}
                >
                  {t("common.cancel")}
                </Button>
                <Button type="submit" pending={form.formState.isSubmitting}>
                  {t("devices.add.submit")}
                </Button>
              </DialogFooter>
            </form>
          </Form>
        )}
      </DialogContent>
    </Dialog>
  );
}

/** New credentials for a TV app (the old password stops working at once). */
export function ResetCredentialsDialog({
  device,
  onOpenChange,
}: {
  device: MyDevice | null;
  onOpenChange: (open: boolean) => void;
}) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const reset = useMeDevicesXtreamCredentials();
  const [issued, setIssued] = useState<MyIssuedCredential | null>(null);
  const [failure, setFailure] = useState<string | null>(null);
  const form = useForm<ResetValues>({
    resolver: zodResolver(resetSchema),
    defaultValues: { mode: "generate", username: "", password: "" },
  });
  const mode = useWatch({ control: form.control, name: "mode" });

  function close(next: boolean): void {
    onOpenChange(next);
    if (!next) {
      setIssued(null);
      setFailure(null);
      form.reset();
    }
  }

  async function onSubmit(values: ResetValues): Promise<void> {
    if (device === null) return;
    setFailure(null);
    try {
      const credential = await reset.mutateAsync({
        id: device.id,
        data:
          values.mode === "choose" ? { username: values.username, password: values.password } : {},
      });
      setIssued(credential);
      void queryClient.invalidateQueries({ queryKey: getMeDevicesListQueryKey() });
    } catch (error) {
      if (!applyApiErrors(error, form.setError)) setFailure(failureKey(error));
    }
  }

  return (
    <Dialog open={device !== null} onOpenChange={close}>
      <DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {issued
              ? t("devices.reset.doneTitle")
              : t("devices.reset.title", { name: device?.name ?? "" })}
          </DialogTitle>
          <DialogDescription>
            {issued ? t("devices.add.doneDescription") : t("devices.reset.description")}
          </DialogDescription>
        </DialogHeader>
        {issued ? (
          <div className="grid gap-5">
            <IssuedCredentialPanel credential={issued} />
            <DialogFooter>
              <Button
                onClick={() => {
                  close(false);
                }}
              >
                {t("devices.add.finish")}
              </Button>
            </DialogFooter>
          </div>
        ) : (
          <Form {...form}>
            <form
              noValidate
              className="grid gap-4"
              onSubmit={(event) => void form.handleSubmit(onSubmit)(event)}
            >
              {failure ? <Alert tone="danger">{t(failure)}</Alert> : null}
              <CredentialFields form={form} mode={mode} />
              <DialogFooter>
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => {
                    close(false);
                  }}
                >
                  {t("common.cancel")}
                </Button>
                <Button type="submit" pending={form.formState.isSubmitting}>
                  {t("devices.reset.submit")}
                </Button>
              </DialogFooter>
            </form>
          </Form>
        )}
      </DialogContent>
    </Dialog>
  );
}
